name: Gradle Plugin Build/Test/Analyze/Publish

on:
  push:
    branches:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Increment version number
        run: ./gradlew incrementMinor
      - name: extract real version
        id: extract_version
        run: echo "::set-output name=v::$(cat version.properties | grep 'semver' | sed -e 's/^version.semver=//')"
      - name: Build
        run: ./gradlew build
      - name: Commit files
        run: |
          git config --local user.email "github-action@saagie.com"
          git config --local user.name "GitHub Action Bot"
          git add version.properties
          git commit -m ":bookmark: Bump new version ${{ steps.extract_version.outputs.v }}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        run: ./gradlew publishPlugins -Dgradle.publish.key=$GRADLE_PUBLISH_KEY -Dgradle.publish.secret=$GRADLE_PUBLISH_SECRET
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
         tag_name: ${{ steps.extract_version.outputs.v }}
         release_name: v${{ steps.extract_version.outputs.v }}
         draft: false
         prerelease: false
      - name: Delete Branch
        uses: jessfraz/branch-cleanup-action@master
        env:
         NO_BRANCH_DELETED_EXIT_CODE: 0
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}